<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
    <title>WireGuard Admin - Installation</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        .gradient-bg {
            background: linear-gradient(135deg, #000000 0%, #1a365d 100%);
        }

        .glass-effect {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }

        .step-indicator {
            transition: all 0.3s ease;
        }

        .step-indicator.active {
            background: #10b981;
            color: white;
        }

        .step-indicator.completed {
            background: #059669;
            color: white;
        }

        .fade-in {
            animation: fadeIn 0.5s ease-in;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(20px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .progress-bar {
            transition: width 0.5s ease;
        }

        .requirement-item {
            transition: all 0.3s ease;
        }

        .requirement-item.passed {
            background: rgba(16, 185, 129, 0.1);
            border-color: #10b981;
        }

        .requirement-item.failed {
            background: rgba(239, 68, 68, 0.1);
            border-color: #ef4444;
        }

        .btn-primary {
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
            transition: all 0.3s ease;
        }

        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(16, 185, 129, 0.3);
        }

        .btn-secondary {
            background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
            transition: all 0.3s ease;
        }

        .btn-secondary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(99, 102, 241, 0.3);
        }

        .vpn-icon {
            animation: float 3s ease-in-out infinite;
        }

        @keyframes float {

            0%,
            100% {
                transform: translateY(0px);
            }

            50% {
                transform: translateY(-10px);
            }
        }

        .loading-spinner {
            animation: spin 1s linear infinite;
        }

        @keyframes spin {
            from {
                transform: rotate(0deg);
            }

            to {
                transform: rotate(360deg);
            }
        }
    </style>
</head>

<body class="gradient-bg min-h-screen">
    <!-- Background Pattern -->
    <div class="absolute inset-0 opacity-10">
        <div class="absolute inset-0" style="background-image: url('data:image/svg+xml,%3Csvg width=\'40\' height=\'40\' viewBox=\'0 0 40 40\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'white\' fill-opacity=\'0.1\'%3E%3Cpath d=\'M20 20c0-11.046-8.954-20-20-20v20h20z\' /%3E%3C/g%3E%3C/svg%3E')">
        </div>
    </div>

    <div class="relative min-h-screen flex items-center justify-center p-4">
        <div class="w-full max-w-4xl">
            <!-- Header -->
            <div class="text-center mb-8">
                <div class="inline-block glass-effect rounded-full p-6 mb-4">
                    <i class="fas fa-shield-alt text-4xl text-white vpn-icon"></i>
                </div>
                <h1 class="text-4xl font-bold text-white mb-2">WireGuard Admin</h1>
                <p class="text-xl text-gray-200">Professional VPN Management Solution</p>
            </div>

            <!-- Installation Container -->
            <div class="glass-effect rounded-2xl p-8 backdrop-blur-lg">
                <!-- Progress Bar -->
                <div class="mb-8">
                    <div class="flex justify-between items-center mb-4">
                        <span class="text-white font-medium">Installation Progress</span>
                        <span class="text-white font-medium" id="progress-text">0%</span>
                    </div>
                    <div class="w-full bg-white bg-opacity-20 rounded-full h-2">
                        <div class="bg-gradient-to-r from-green-400 to-green-600 h-2 rounded-full progress-bar"
                            style="width: 0%" id="progress-bar"></div>
                    </div>
                </div>

                <!-- Step Indicators -->
                <div class="flex justify-center mb-8">
                    <div class="flex items-center space-x-4" id="step-indicators">
                        <!-- Generated by JavaScript -->
                    </div>
                </div>

                <!-- Installation Content -->
                <div id="installation-content" class="fade-in">
                    <!-- Content will be loaded here -->
                </div>
            </div>

            <!-- Footer -->
            <div class="text-center mt-8">
                <p class="text-gray-300">
                    <i class="fas fa-code mr-2"></i>
                    Built with security and performance in mind
                </p>
            </div>
        </div>
    </div>

    <script>
        class WireGuardInstaller {
            constructor() {
                this.currentStep = 'welcome';
                this.steps = {};
                this.init();
            }

            async init() {
                await this.fetchSteps();
                await this.determineCurrentStep();
                this.renderStepIndicators();
                await this.loadCurrentStep();
            }

            async fetchSteps() {
                try {
                    // Changed from install.php to install_process.php
                    const res = await fetch('install_process.php', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: 'action=get_steps'
                    });
                    const data = await res.json();
                    if (data.success && data.steps) {
                        this.steps = data.steps;
                    } else {
                        // Fallback to static steps if backend fails
                        this.steps = {
                            'welcome': {
                                title: 'Welcome',
                                icon: 'fas fa-home',
                                description: 'Welcome to WireGuard Admin installation wizard'
                            },
                            'requirements': {
                                title: 'Requirements',
                                icon: 'fas fa-check-circle',
                                description: 'Checking system requirements'
                            },
                            'database': {
                                title: 'Database',
                                icon: 'fas fa-database',
                                description: 'Database setup'
                            },
                            'admin_account': {
                                title: 'Admin Account',
                                icon: 'fas fa-user-shield',
                                description: 'Create admin account'
                            },
                            'wireguard_config': {
                                title: 'Configuration',
                                icon: 'fas fa-cog',
                                description: 'WireGuard configuration'
                            },
                            'security': {
                                title: 'Security',
                                icon: 'fas fa-lock',
                                description: 'Security settings'
                            },
                            'complete': {
                                title: 'Complete',
                                icon: 'fas fa-check',
                                description: 'Installation complete'
                            }
                        };
                    }
                } catch (e) {
                    console.error('Error fetching steps:', e);
                    // Fallback to static steps
                    this.steps = {
                        'welcome': {
                            title: 'Welcome',
                            icon: 'fas fa-home',
                            description: 'Welcome to WireGuard Admin installation wizard'
                        },
                        'requirements': {
                            title: 'Requirements',
                            icon: 'fas fa-check-circle',
                            description: 'Checking system requirements'
                        },
                        'database': {
                            title: 'Database',
                            icon: 'fas fa-database',
                            description: 'Database setup'
                        },
                        'admin_account': {
                            title: 'Admin Account',
                            icon: 'fas fa-user-shield',
                            description: 'Create admin account'
                        },
                        'wireguard_config': {
                            title: 'Configuration',
                            icon: 'fas fa-cog',
                            description: 'WireGuard configuration'
                        },
                        'security': {
                            title: 'Security',
                            icon: 'fas fa-lock',
                            description: 'Security settings'
                        },
                        'complete': {
                            title: 'Complete',
                            icon: 'fas fa-check',
                            description: 'Installation complete'
                        }
                    };
                }
            }

            async determineCurrentStep() {
                try {
                    // Changed from install.php to install_process.php
                    const res = await fetch('install_process.php', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: 'action=get_current_step'
                    });
                    const data = await res.json();
                    if (data.success && data.step) {
                        this.currentStep = data.step;
                    }
                } catch (e) {
                    console.error('Error determining current step:', e);
                    // Default to welcome step
                    this.currentStep = 'welcome';
                }
            }

            renderStepIndicators() {
                const container = document.getElementById('step-indicators');
                const stepKeys = Object.keys(this.steps);
                container.innerHTML = stepKeys.map((stepKey, index) => {
                    const step = this.steps[stepKey];
                    const isActive = stepKey === this.currentStep;
                    const isCompleted = stepKeys.indexOf(this.currentStep) > index;
                    let classes = 'step-indicator w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium';
                    if (isCompleted) {
                        classes += ' completed';
                    } else if (isActive) {
                        classes += ' active';
                    } else {
                        classes += ' bg-white bg-opacity-20 text-gray-300';
                    }
                    return `
                        <div class="flex items-center">
                            <div class="${classes}">
                                <i class="${step.icon}"></i>
                            </div>
                            ${index < stepKeys.length - 1 ? '<div class="w-8 h-0.5 bg-white bg-opacity-20 mx-2"></div>' : ''}
                        </div>
                    `;
                }).join('');
            }

            async loadCurrentStep() {
                try {
                    const stepInfo = this.steps[this.currentStep];
                    let content;
                    if (this.currentStep === 'requirements') {
                        content = this.generateRequirementsPlaceholder(stepInfo);
                        this.renderStepContent(content);
                        await this.loadRequirements();
                    } else {
                        content = this.generateStepContent(this.currentStep, stepInfo);
                        this.renderStepContent(content);
                    }
                    this.calculateProgress().then(progress => {
                        this.updateProgress(progress);
                    });
                } catch (error) {
                    this.showError('Failed to load installation step: ' + error.message);
                }
            }

            generateStepContent(step, stepInfo) {
                switch (step) {
                    case 'welcome':
                        return this.generateWelcomeContent(stepInfo);
                    case 'database':
                        return this.generateDatabaseContent(stepInfo);
                    case 'admin_account':
                        return this.generateAdminAccountContent(stepInfo);
                    case 'wireguard_config':
                        return this.generateWireGuardConfigContent(stepInfo);
                    case 'security':
                        return this.generateSecurityContent(stepInfo);
                    case 'complete':
                        return this.generateCompleteContent(stepInfo);
                    default:
                        return '<div class="text-center text-white">Unknown step</div>';
                }
            }

            generateWelcomeContent(stepInfo) {
                return `
                        const text = await res.text();
                        let data = null;
                        try {
                            data = JSON.parse(text);
                        } catch (jsonErr) {
                            console.error('Progress response not JSON:', text);
                            throw new Error('Progress response not JSON');
                        }
                    <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                    <p class="text-xl text-gray-200 mb-8">${stepInfo.description}</p>
                    
                    <div class="bg-white bg-opacity-10 rounded-xl p-6 mb-8">
                        <i class="fas fa-shield-alt text-4xl text-green-400 mb-4"></i>
                        <p class="text-gray-200 mb-4">
                            Welcome to the WireGuard Admin installation wizard. This will guide you through setting up your VPN management system.
                        </p>
                        <p class="text-gray-200">
                            Before starting, make sure you have:
                        </p>
                        <ul class="list-disc list-inside text-gray-200 mt-2 space-y-1">
                            <li>MySQL database credentials</li>
                            <li>WireGuard installed on your server</li>
                            <li>Server IP address or domain name</li>
                        </ul>
                    </div>
                    
                    <button id="next-btn" class="btn-primary text-white px-8 py-3 rounded-lg font-semibold">
                        <i class="fas fa-rocket mr-2"></i>Start Installation
                    </button>
                </div>`;
            }

            generateRequirementsPlaceholder(stepInfo) {
                return `
                <div class="text-center">
                    <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                    <p class="text-xl text-gray-200 mb-8">${stepInfo.description}</p>
                    
                    <div class="space-y-4 mb-8">
                        <div class="requirement-item bg-white bg-opacity-10 rounded-lg p-4 border-2">
                            <div class="flex items-center justify-between">
                                <div class="flex items-center">
                                    <i class="fas fa-spinner loading-spinner mr-3"></i>
                                    <span class="text-white font-medium">Checking requirements...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>`;
            }

            async loadRequirements() {
                let requirements = [];
                let allPassed = false;
                let backendFailed = false;
                try {
                    const response = await fetch('install_process.php', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: 'action=check_requirements'
                    });
                    const data = await response.json();
                    console.log('Requirements data:', data);
                    if (data.success && data.requirements) {
                        requirements = data.requirements;
                        allPassed = data.all_passed || requirements.every(req => req.status);
                    } else {
                        backendFailed = true;
                    }
                } catch (error) {
                    backendFailed = true;
                }

                // Fallback to static requirements if backend fails
                if (backendFailed) {
                    requirements = [
                        { name: 'PHP 7.4+', status: true, current: 'Detected', message: '' },
                        { name: 'WireGuard', status: false, current: 'Not detected', message: 'Install WireGuard on your server.' },
                        { name: 'MySQL Extension', status: true, current: 'Available', message: '' },
                        { name: 'Write Permissions', status: true, current: 'Writable', message: '' },
                        { name: 'JSON Extension', status: true, current: 'Available', message: '' }
                    ];
                    allPassed = requirements.every(req => req.status);
                }

                let content = `
            <div class="text-center">
                <h2 class="text-3xl font-bold text-white mb-4">${this.steps.requirements.title}</h2>
                <p class="text-xl text-gray-200 mb-8">${this.steps.requirements.description}</p>
                <div class="space-y-4 mb-8">`;
                requirements.forEach(req => {
                    const statusClass = req.status ? 'passed' : 'failed';
                    const iconClass = req.status ? 'fas fa-check-circle text-green-500' : 'fas fa-times-circle text-red-500';
                    const bgClass = req.status ? 'bg-green-500 bg-opacity-20' : 'bg-red-500 bg-opacity-20';
                    content += `
                <div class="requirement-item ${statusClass} ${bgClass} rounded-lg p-4 border-2">
                    <div class="flex items-center justify-between">
                        <div class="flex items-center">
                            <i class="${iconClass} mr-3"></i>
                            <span class="text-white font-medium">${req.name}</span>
                        </div>
                        <span class="text-gray-300 text-sm">${req.current}</span>
                    </div>
                    ${req.message ? `<div class="text-xs mt-2 text-gray-300">${req.message}</div>` : ''}
                </div>`;
                });
                content += `</div>`;
                if (allPassed) {
                    content += `
                <div class="bg-green-500 bg-opacity-20 rounded-lg p-4 mb-6">
                    <div class="flex items-center justify-center text-green-400">
                        <i class="fas fa-check-circle mr-2"></i>
                        <span>All requirements passed!</span>
                    </div>
                </div>
                <button id="next-btn" class="btn-primary text-white px-8 py-3 rounded-lg font-semibold">
                    <i class="fas fa-arrow-right mr-2"></i>Continue
                </button>`;
                } else {
                    content += `
                <div class="bg-red-500 bg-opacity-20 rounded-lg p-4 mb-6">
                    <div class="flex items-center justify-center text-red-400">
                        <i class="fas fa-exclamation-triangle mr-2"></i>
                        <span>Please fix the requirements above before continuing</span>
                    </div>
                </div>
                <button onclick="location.reload()" class="btn-secondary text-white px-8 py-3 rounded-lg font-semibold">
                    <i class="fas fa-refresh mr-2"></i>Recheck
                </button>`;
                }
                content += `</div>`;
                document.getElementById('installation-content').innerHTML = content;
                this.bindEventListeners();
            }

            generateDatabaseContent(stepInfo) {
                return `
                <div class="text-center">
                    <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                    <p class="text-xl text-gray-200 mb-8">${stepInfo.description}</p>
                    <form class="max-w-md mx-auto space-y-6" id="mysql-form">
                        <div class="bg-white bg-opacity-10 rounded-xl p-6 mb-8">
                            <i class="fas fa-database text-4xl text-blue-400 mb-4"></i>
                            <p class="text-gray-200 mb-4">
                                Please enter your <b>MySQL</b> database connection details. <br>
                            </p>
                        </div>
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-server mr-2"></i>MySQL Host
                            </label>
                            <input type="text" name="db_host" value="localhost" required
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="localhost">
                        </div>
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-database mr-2"></i>Database Name
                            </label>
                            <input type="text" name="db_name" value="wireguard_admin" required
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="wireguard_admin">
                        </div>
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-user mr-2"></i>MySQL Username
                            </label>
                            <input type="text" name="db_user" value="root" required
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="root">
                        </div>
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-key mr-2"></i>MySQL Password
                            </label>
                            <input type="password" name="db_pass"
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="Password">
                        </div>
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-plug mr-2"></i>MySQL Port
                            </label>
                            <input type="number" name="db_port" value="3306" required
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="3306">
                        </div>
                        <button type="submit" class="w-full btn-primary text-white py-3 rounded-lg font-semibold">
                            <i class="fas fa-database mr-2"></i>Save & Test Connection
                        </button>
                    </form>
                </div>`;
            }

            generateAdminAccountContent(stepInfo) {
                return `
                <div>
                    <div class="text-center mb-8">
                        <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                        <p class="text-xl text-gray-200">${stepInfo.description}</p>
                    </div>
                    
                    <form class="max-w-md mx-auto space-y-6" id="admin-form">
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-user mr-2"></i>Username
                            </label>
                            <input type="text" name="username" required 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="Enter admin username">
                        </div>
                        
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-envelope mr-2"></i>Email (Optional)
                            </label>
                            <input type="email" name="email" 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="admin@example.com">
                        </div>
                        
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-lock mr-2"></i>Password
                            </label>
                            <input type="password" name="password" required minlength="8"
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="Minimum 8 characters">
                        </div>
                        
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-lock mr-2"></i>Confirm Password
                            </label>
                            <input type="password" name="confirm_password" required minlength="8"
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="Confirm your password">
                        </div>
                        
                        <div class="bg-yellow-500 bg-opacity-20 rounded-lg p-4">
                            <div class="flex items-start text-yellow-200">
                                <i class="fas fa-exclamation-triangle mr-2 mt-1"></i>
                                <div class="text-sm">
                                    <strong>Important:</strong> Remember these credentials! You'll use them to access the admin panel.
                                </div>
                            </div>
                        </div>
                        
                        <button type="submit" class="w-full btn-primary text-white py-3 rounded-lg font-semibold">
                            <i class="fas fa-user-plus mr-2"></i>Create Admin Account
                        </button>
                    </form>
                </div>`;
            }

            generateWireGuardConfigContent(stepInfo) {
                return `
                <div>
                    <div class="text-center mb-8">
                        <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                        <p class="text-xl text-gray-200">${stepInfo.description}</p>
                    </div>
                    
                    <form class="max-w-md mx-auto space-y-6" id="wireguard-form">
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-server mr-2"></i>Server IP/Domain
                            </label>
                            <input type="text" name="server_ip" required 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="vpn.yourdomain.com or 1.2.3.4">
                        </div>
                        
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-plug mr-2"></i>Server Port
                            </label>
                            <input type="number" name="server_port" value="51820" required 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="51820">
                        </div>
                        
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-network-wired mr-2"></i>VPN Subnet
                            </label>
                            <input type="text" name="subnet" value="10.0.0.0/24" required 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="10.0.0.0/24">
                        </div>
                        
                        <div class="bg-blue-500 bg-opacity-20 rounded-lg p-4">
                            <div class="flex items-start text-blue-200">
                                <i class="fas fa-info-circle mr-2 mt-1"></i>
                                <div class="text-sm">
                                    <strong>Note:</strong> Make sure the server IP/domain is accessible from the internet and port 51820 is open in your firewall.
                                </div>
                            </div>
                        </div>
                        
                        <button type="submit" class="w-full btn-primary text-white py-3 rounded-lg font-semibold">
                            <i class="fas fa-cog mr-2"></i>Save Configuration
                        </button>
                    </form>
                </div>`;
            }

            generateSecurityContent(stepInfo) {
                return `
                <div>
                    <div class="text-center mb-8">
                        <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                        <p class="text-xl text-gray-200">${stepInfo.description}</p>
                    </div>
                    
                    <form class="max-w-md mx-auto space-y-6" id="security-form">
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-clock mr-2"></i>Session Timeout (seconds)
                            </label>
                            <input type="number" name="session_timeout" value="1800" required 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="1800">
                            <small class="text-gray-300 text-xs">Default: 30 minutes (1800 seconds)</small>
                        </div>
                        
                        <div>
                            <label class="block text-white font-medium mb-2">
                                <i class="fas fa-history mr-2"></i>Maximum Login Attempts
                            </label>
                            <input type="number" name="max_login_attempts" value="5" required 
                                   class="w-full px-4 py-3 bg-white bg-opacity-20 border border-white border-opacity-30 rounded-lg text-white placeholder-gray-300 focus:outline-none focus:border-green-400"
                                   placeholder="5">
                        </div>
                        
                        <div class="flex items-center">
                            <input type="checkbox" name="enable_logging" value="1" checked 
                                   class="mr-3 w-4 h-4 text-green-600 bg-white bg-opacity-20 border-gray-300 rounded focus:ring-green-500">
                            <label class="text-white font-medium">
                                <i class="fas fa-file-alt mr-2"></i>Enable Audit Logging
                            </label>
                        </div>
                        
                        <div class="bg-green-500 bg-opacity-20 rounded-lg p-4">
                            <div class="flex items-start text-green-200">
                                <i class="fas fa-shield-alt mr-2 mt-1"></i>
                                <div class="text-sm">
                                    <strong>Security Features:</strong>
                                    <ul class="list-disc list-inside mt-2 space-y-1">
                                        <li>CSRF protection</li>
                                        <li>Password hashing with bcrypt</li>
                                        <li>Session security</li>
                                        <li>Audit trail logging</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                        <button type="submit" class="w-full btn-primary text-white py-3 rounded-lg font-semibold">
                            <i class="fas fa-shield-alt mr-2"></i>Apply Security Settings
                        </button>
                    </form>
                </div>`;
            }

            generateCompleteContent(stepInfo) {
                return `
                <div class="text-center">
                    <div class="mb-8">
                        <i class="fas fa-check-circle text-6xl text-green-400 mb-4"></i>
                        <h2 class="text-3xl font-bold text-white mb-4">${stepInfo.title}</h2>
                        <p class="text-xl text-gray-200 mb-6">${stepInfo.description}</p>
                    </div>
                    
                    <div class="bg-green-500 bg-opacity-20 rounded-xl p-6 mb-8">
                        <h3 class="text-xl font-semibold text-white mb-4">Installation Summary</h3>
                        <div class="text-left space-y-2 text-gray-200">
                            <div class="flex items-center">
                                <i class="fas fa-check text-green-400 mr-3"></i>
                                Database created and configured
                            </div>
                            <div class="flex items-center">
                                <i class="fas fa-check text-green-400 mr-3"></i>
                                Admin account set up
                            </div>
                            <div class="flex items-center">
                                <i class="fas fa-check text-green-400 mr-3"></i>
                                WireGuard configuration saved
                            </div>
                            <div class="flex items-center">
                                <i class="fas fa-check text-green-400 mr-3"></i>
                                Security settings applied
                            </div>
                        </div>
                    </div>
                    
                    <div class="bg-blue-500 bg-opacity-20 rounded-xl p-4 mb-8">
                        <h4 class="text-lg font-semibold text-white mb-2">Next Steps</h4>
                        <div class="text-gray-200 text-sm space-y-1">
                            <p>1. Set up WireGuard server configuration</p>
                            <p>2. Configure firewall rules</p>
                            <p>3. Start creating VPN peers</p>
                        </div>
                    </div>
                    
                    <button id="complete-btn" class="btn-primary text-white px-8 py-3 rounded-lg font-semibold">
                        <i class="fas fa-tachometer-alt mr-2"></i>Go to Dashboard
                    </button>
                </div>`;
            }

            renderStepContent(content) {
                document.getElementById('installation-content').innerHTML = content;
                this.bindEventListeners();
            }

            bindEventListeners() {
                // Form submissions
                const forms = document.querySelectorAll('form');
                forms.forEach(form => {
                    form.addEventListener('submit', this.handleFormSubmit.bind(this));
                });

                // Next/Previous buttons
                const nextBtn = document.getElementById('next-btn');
                const prevBtn = document.getElementById('prev-btn');
                const completeBtn = document.getElementById('complete-btn');

                if (nextBtn) {
                    nextBtn.addEventListener('click', this.nextStep.bind(this));
                }

                if (prevBtn) {
                    prevBtn.addEventListener('click', this.prevStep.bind(this));
                }

                if (completeBtn) {
                    completeBtn.addEventListener('click', () => {
                        window.location.href = 'admin/';
                    });
                }
            }

            async handleFormSubmit(event) {
                event.preventDefault();
                const form = event.target;
                const formData = new FormData(form);
                const data = Object.fromEntries(formData);
                
                // Validate passwords match for admin account
                if (form.id === 'admin-form' && data.password !== data.confirm_password) {
                    this.showError('Passwords do not match');
                    return;
                }
                
                await this.processStep(data);
            }

            async processStep(data = {}) {
                try {
                    this.showLoading(true);
                    
                    // Send form data to backend - changed from install.php to install_process.php
                    const formData = new URLSearchParams();
                    formData.append('action', 'complete_step');
                    formData.append('step', this.currentStep);
                    formData.append('data', JSON.stringify(data));
                    
                    const res = await fetch('install_process.php', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: formData
                    });
                    
                    const result = await res.json();
                    if (result.success) {
                        this.showSuccess(result.message || 'Step completed successfully!');
                        setTimeout(() => {
                            this.nextStep();
                        }, 1000);
                    } else {
                        this.showError(result.message || 'Processing failed');
                    }
                } catch (error) {
                    this.showError('Processing failed: ' + error.message);
                } finally {
                    this.showLoading(false);
                }
            }

            async nextStep() {
                const stepKeys = Object.keys(this.steps);
                const currentIndex = stepKeys.indexOf(this.currentStep);

                if (currentIndex < stepKeys.length - 1) {
                    this.currentStep = stepKeys[currentIndex + 1];
                    this.renderStepIndicators();
                    await this.loadCurrentStep();
                }
            }

            prevStep() {
                const stepKeys = Object.keys(this.steps);
                const currentIndex = stepKeys.indexOf(this.currentStep);

                if (currentIndex > 0) {
                    this.currentStep = stepKeys[currentIndex - 1];
                    this.renderStepIndicators();
                    this.loadCurrentStep();
                }
            }

            async calculateProgress() {
                try {
                    // Changed from install.php to install_process.php
                    const res = await fetch('install_process.php', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: 'action=get_progress'
                    });
                    const data = await res.json();
                    if (data.success && data.progress !== undefined) {
                        return data.progress;
                    }
                } catch (e) {
                    console.error('Error getting progress:', e);
                }
                
                // Fallback calculation
                const stepKeys = Object.keys(this.steps);
                const currentIndex = stepKeys.indexOf(this.currentStep);
                return Math.round((currentIndex / (stepKeys.length - 1)) * 100);
            }

            updateProgress(progress) {
                const progressBar = document.getElementById('progress-bar');
                const progressText = document.getElementById('progress-text');

                progressBar.style.width = progress + '%';
                progressText.textContent = progress + '%';
            }

            showLoading(show) {
                const buttons = document.querySelectorAll('button');
                buttons.forEach(btn => {
                    if (show) {
                        btn.disabled = true;
                        if (btn.innerHTML.includes('Next') || btn.innerHTML.includes('Install') ||
                            btn.innerHTML.includes('Create') || btn.innerHTML.includes('Save') ||
                            btn.innerHTML.includes('Apply')) {
                            btn.innerHTML = '<i class="fas fa-spinner loading-spinner mr-2"></i>Processing...';
                        }
                    } else {
                        btn.disabled = false;
                        // Restore original button text
                        this.loadCurrentStep();
                    }
                });
            }

            showSuccess(message) {
                this.showMessage(message, 'success');
            }

            showError(message) {
                this.showMessage(message, 'error');
            }

            showMessage(message, type) {
                const alertClass = type === 'success' ? 'bg-green-500' : 'bg-red-500';
                const iconClass = type === 'success' ? 'fas fa-check-circle' : 'fas fa-exclamation-triangle';

                const alert = document.createElement('div');
                alert.className = `fixed top-4 right-4 ${alertClass} text-white px-6 py-4 rounded-lg shadow-lg z-50 fade-in`;
                alert.innerHTML = `
                    <div class="flex items-center">
                        <i class="${iconClass} mr-2"></i>
                        <span>${message}</span>
                    </div>
                `;

                document.body.appendChild(alert);

                setTimeout(() => {
                    alert.remove();
                }, 5000);
            }
        }

        // Initialize installer when page loads
        document.addEventListener('DOMContentLoaded', () => {
            new WireGuardInstaller();
        });
    </script>
</body>

</html>