<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WireGuard Admin - Installation</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        .gradient-bg {
            background: linear-gradient(135deg, #000000ff 0%, #000000ff 100%);
        }
        
        .glass-effect {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
        
        .step-indicator {
            transition: all 0.3s ease;
        }
        
        .step-indicator.active {
            background: #10b981;
            color: white;
        }
        
        .step-indicator.completed {
            background: #059669;
            color: white;
        }
        
        .fade-in {
            animation: fadeIn 0.5s ease-in;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        .progress-bar {
            transition: width 0.5s ease;
        }
        
        .requirement-item {
            transition: all 0.3s ease;
        }
        
        .requirement-item.passed {
            background: #000000ff;
            border-color: #25a955ff;
        }
        
        .requirement-item.failed {
            background: #000000ff;
            border-color: #ef4444;
        }
        
        .btn-primary {
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
            transition: all 0.3s ease;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(16, 185, 129, 0.3);
        }
        
        .btn-secondary {
            background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
            transition: all 0.3s ease;
        }
        
        .btn-secondary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(99, 102, 241, 0.3);
        }
        
        .vpn-icon {
            animation: float 3s ease-in-out infinite;
        }
        
        @keyframes float {
            0%, 100% { transform: translateY(0px); }
            50% { transform: translateY(-10px); }
        }
        
        .loading-spinner {
            animation: spin 1s linear infinite;
        }
        
        @keyframes spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
        }
    </style>
</head>
<body class="gradient-bg min-h-screen">
    <!-- Background Pattern -->
    <div class="absolute inset-0 opacity-10">
        <div class="absolute inset-0" style="background-image: url('data:image/svg+xml,<svg width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><g fill="white" fill-opacity="0.1"><path d="M20 20c0-11.046-8.954-20-20-20v20h20z"/></g></svg>')"></div>
    </div>

    <div class="relative min-h-screen flex items-center justify-center p-4">
        <div class="w-full max-w-4xl">
            <!-- Header -->
            <div class="text-center mb-8">
                <div class="inline-block glass-effect rounded-full p-6 mb-4">
                    <i class="fas fa-shield-alt text-4xl text-white vpn-icon"></i>
                </div>
                <h1 class="text-4xl font-bold text-white mb-2">WireGuard Admin</h1>
                <p class="text-xl text-gray-200">Professional VPN Management Solution</p>
            </div>

            <!-- Installation Container -->
            <div class="glass-effect rounded-2xl p-8 backdrop-blur-lg">
                <!-- Progress Bar -->
                <div class="mb-8">
                    <div class="flex justify-between items-center mb-4">
                        <span class="text-white font-medium">Installation Progress</span>
                        <span class="text-white font-medium" id="progress-text">0%</span>
                    </div>
                    <div class="w-full bg-white bg-opacity-20 rounded-full h-2">
                        <div class="bg-gradient-to-r from-green-400 to-green-600 h-2 rounded-full progress-bar" 
                             style="width: 0%" id="progress-bar"></div>
                    </div>
                </div>

                <!-- Step Indicators -->
                <div class="flex justify-center mb-8">
                    <div class="flex items-center space-x-4" id="step-indicators">
                        <!-- Generated by JavaScript -->
                    </div>
                </div>

                <!-- Installation Content -->
                <div id="installation-content" class="fade-in">
                    <!-- Content will be loaded here -->
                </div>
            </div>

            <!-- Footer -->
            <div class="text-center mt-8">
                <p class="text-gray-300">
                    <i class="fas fa-code mr-2"></i>
                    Built with security and performance in mind
                </p>
            </div>
        </div>
    </div>

    <script>
        class WireGuardInstaller {
            constructor() {
                this.currentStep = 'welcome';
                this.steps = {
                    'welcome': { title: 'Welcome', icon: 'fas fa-home' },
                    'requirements': { title: 'Requirements', icon: 'fas fa-check-circle' },
                    'database': { title: 'Database', icon: 'fas fa-database' },
                    'admin_account': { title: 'Admin Account', icon: 'fas fa-user-shield' },
                    'wireguard_config': { title: 'Configuration', icon: 'fas fa-cog' },
                    'security': { title: 'Security', icon: 'fas fa-lock' },
                    'complete': { title: 'Complete', icon: 'fas fa-check' }
                };
                this.init();
            }

            init() {
                this.renderStepIndicators();
                this.loadCurrentStep();
            }

            renderStepIndicators() {
                const container = document.getElementById('step-indicators');
                const stepKeys = Object.keys(this.steps);
                
                container.innerHTML = stepKeys.map((stepKey, index) => {
                    const step = this.steps[stepKey];
                    const isActive = stepKey === this.currentStep;
                    const isCompleted = stepKeys.indexOf(this.currentStep) > index;
                    
                    let classes = 'step-indicator w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium';
                    
                    if (isCompleted) {
                        classes += ' completed';
                    } else if (isActive) {
                        classes += ' active';
                    } else {
                        classes += ' bg-white bg-opacity-20 text-gray-300';
                    }
                    
                    return `
                        <div class="flex items-center">
                            <div class="${classes}">
                                <i class="${step.icon}"></i>
                            </div>
                            ${index < stepKeys.length - 1 ? '<div class="w-8 h-0.5 bg-white bg-opacity-20 mx-2"></div>' : ''}
                        </div>
                    `;
                }).join('');
            }

            async loadCurrentStep() {
                try {
                    const response = await fetch('install_handler.php', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            action: 'get_step',
                            step: this.currentStep
                        })
                    });

                    const data = await response.json();
                    
                    if (data.success) {
                        this.renderStepContent(data.content);
                        this.updateProgress(data.progress);
                    } else {
                        this.showError(data.message);
                    }
                } catch (error) {
                    this.showError('Failed to load installation step');
                }
            }

            renderStepContent(content) {
                document.getElementById('installation-content').innerHTML = content;
                this.bindEventListeners();
            }

            bindEventListeners() {
                // Form submissions
                const forms = document.querySelectorAll('form');
                forms.forEach(form => {
                    form.addEventListener('submit', this.handleFormSubmit.bind(this));
                });

                // Next/Previous buttons
                const nextBtn = document.getElementById('next-btn');
                const prevBtn = document.getElementById('prev-btn');
                
                if (nextBtn) {
                    nextBtn.addEventListener('click', this.nextStep.bind(this));
                }
                
                if (prevBtn) {
                    prevBtn.addEventListener('click', this.prevStep.bind(this));
                }
            }

            async handleFormSubmit(event) {
                event.preventDefault();
                
                const form = event.target;
                const formData = new FormData(form);
                const data = Object.fromEntries(formData);
                
                await this.processStep(data);
            }

            async processStep(data = {}) {
                try {
                    this.showLoading(true);
                    
                    const response = await fetch('install_handler.php', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            action: 'process_step',
                            step: this.currentStep,
                            data: data
                        })
                    });

                    const result = await response.json();
                    
                    if (result.success) {
                        this.showSuccess(result.message);
                        setTimeout(() => {
                            this.nextStep();
                        }, 1500);
                    } else {
                        this.showError(result.message);
                    }
                } catch (error) {
                    this.showError('Processing failed: ' + error.message);
                } finally {
                    this.showLoading(false);
                }
            }

            nextStep() {
                const stepKeys = Object.keys(this.steps);
                const currentIndex = stepKeys.indexOf(this.currentStep);
                
                if (currentIndex < stepKeys.length - 1) {
                    this.currentStep = stepKeys[currentIndex + 1];
                    this.renderStepIndicators();
                    this.loadCurrentStep();
                }
            }

            prevStep() {
                const stepKeys = Object.keys(this.steps);
                const currentIndex = stepKeys.indexOf(this.currentStep);
                
                if (currentIndex > 0) {
                    this.currentStep = stepKeys[currentIndex - 1];
                    this.renderStepIndicators();
                    this.loadCurrentStep();
                }
            }

            updateProgress(progress) {
                const progressBar = document.getElementById('progress-bar');
                const progressText = document.getElementById('progress-text');
                
                progressBar.style.width = progress + '%';
                progressText.textContent = progress + '%';
            }

            showLoading(show) {
                const buttons = document.querySelectorAll('button');
                buttons.forEach(btn => {
                    if (show) {
                        btn.disabled = true;
                        if (btn.innerHTML.includes('Next') || btn.innerHTML.includes('Install')) {
                            btn.innerHTML = '<i class="fas fa-spinner loading-spinner mr-2"></i>Processing...';
                        }
                    } else {
                        btn.disabled = false;
                        // Restore original button text
                        this.loadCurrentStep();
                    }
                });
            }

            showSuccess(message) {
                this.showMessage(message, 'success');
            }

            showError(message) {
                this.showMessage(message, 'error');
            }

            showMessage(message, type) {
                const alertClass = type === 'success' ? 'bg-green-500' : 'bg-red-500';
                const iconClass = type === 'success' ? 'fas fa-check-circle' : 'fas fa-exclamation-triangle';
                
                const alert = document.createElement('div');
                alert.className = `fixed top-4 right-4 ${alertClass} text-white px-6 py-4 rounded-lg shadow-lg z-50 fade-in`;
                alert.innerHTML = `
                    <div class="flex items-center">
                        <i class="${iconClass} mr-2"></i>
                        <span>${message}</span>
                    </div>
                `;
                
                document.body.appendChild(alert);
                
                setTimeout(() => {
                    alert.remove();
                }, 5000);
            }
        }

        // Initialize installer when page loads
        document.addEventListener('DOMContentLoaded', () => {
            new WireGuardInstaller();
        });
    </script>
</body>
</html>
